import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'  

export default function Home({ locale }) {
  const { t } = useTranslation();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          i18n current langugage: 
          <br/><br/>
          {locale}
        </h1>
        <hr />
        <h2>
          from local files:
          <br/><br/>
          {t('home:welcome_msg')}
        </h2>
        <hr />
        <h2>
          from local files:
          <br/><br/>
          {t('home:second_test_msg')}
        </h2>
      </main>
    </div>
  )
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['home']))
    }
  }
}